// ============================================================
// GET  /api/marketplace  — list marketplace items
// ============================================================

import { NextRequest, NextResponse } from 'next/server'
import type { MarketplaceItem } from '@/lib/types'

const now = new Date().toISOString()

const SEED_ITEMS: MarketplaceItem[] = [
  {
    id: 'mkt-001',
    name: 'Research Agent',
    description: 'Finds, synthesizes, and summarizes information from the web with source citations.',
    long_description: 'A specialist agent pre-configured for deep research tasks. Uses web search, PDF reading, and structured note-taking to produce detailed research briefs.',
    category: 'agents',
    author: 'Space OS Team',
    author_verified: true,
    price_monthly: null,
    installs: 4821,
    rating: 4.8,
    rating_count: 312,
    tags: ['research', 'web-search', 'summarization'],
    icon_color: 'blue',
    featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mkt-002',
    name: 'Code Review Agent',
    description: 'Reviews pull requests for bugs, security issues, and code quality violations.',
    long_description: 'Automated code review agent that integrates with GitHub PRs. Catches bugs, enforces style guides, and suggests refactors before human review.',
    category: 'agents',
    author: 'Space OS Team',
    author_verified: true,
    price_monthly: null,
    installs: 3240,
    rating: 4.7,
    rating_count: 218,
    tags: ['code-review', 'github', 'security'],
    icon_color: 'purple',
    featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mkt-003',
    name: 'Content Writer Agent',
    description: 'Produces SEO-optimized blog posts, landing pages, and marketing copy at scale.',
    long_description: 'A high-quality content generation agent trained on marketing best practices. Handles briefs, outlines, drafts, and revisions in one pipeline.',
    category: 'agents',
    author: 'ContentForge',
    author_verified: true,
    price_monthly: 900,
    installs: 2105,
    rating: 4.6,
    rating_count: 145,
    tags: ['content', 'seo', 'marketing', 'copywriting'],
    icon_color: 'orange',
    featured: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mkt-004',
    name: 'Data Analyst Agent',
    description: 'Queries databases, generates charts, and writes analytical reports from raw data.',
    long_description: 'Connect to Postgres, BigQuery, or CSV files and get instant analytical reports with charts and actionable insights.',
    category: 'agents',
    author: 'DataStack Labs',
    author_verified: true,
    price_monthly: 1200,
    installs: 1890,
    rating: 4.9,
    rating_count: 204,
    tags: ['data', 'analytics', 'sql', 'charts'],
    icon_color: 'green',
    featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mkt-005',
    name: 'QA Tester Agent',
    description: 'Writes and runs end-to-end tests using Playwright, flags regressions automatically.',
    long_description: 'Automatically generates E2E test suites from your app URL or spec files. Runs Playwright tests in CI and surfaces regressions with screenshots.',
    category: 'agents',
    author: 'Space OS Team',
    author_verified: true,
    price_monthly: null,
    installs: 1432,
    rating: 4.5,
    rating_count: 89,
    tags: ['testing', 'playwright', 'qa', 'automation'],
    icon_color: 'red',
    featured: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mkt-006',
    name: 'Web Search Tool',
    description: 'Real-time web search powered by Perplexity — returns structured results with sources.',
    long_description: 'Give any agent access to live web search. Returns ranked, deduplicated results with URL, title, snippet, and publish date.',
    category: 'tools',
    author: 'Space OS Team',
    author_verified: true,
    price_monthly: null,
    installs: 8902,
    rating: 4.9,
    rating_count: 541,
    tags: ['search', 'web', 'perplexity'],
    icon_color: 'sky',
    featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mkt-007',
    name: 'GitHub Tool',
    description: 'Read repos, open issues, create PRs, and review diffs directly from agent tasks.',
    long_description: 'Full GitHub API wrapper as an agent tool. Supports reading files, creating commits, opening PRs, and managing issues with workspace-level auth.',
    category: 'tools',
    author: 'Space OS Team',
    author_verified: true,
    price_monthly: null,
    installs: 6215,
    rating: 4.8,
    rating_count: 389,
    tags: ['github', 'git', 'code', 'devops'],
    icon_color: 'gray',
    featured: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mkt-008',
    name: 'Slack Notifier',
    description: 'Posts task updates, alerts, and agent outputs to any Slack channel or DM.',
    long_description: 'Lightweight Slack integration tool. Post messages, create threads, upload files, and react to messages from any agent in your workspace.',
    category: 'tools',
    author: 'Space OS Team',
    author_verified: true,
    price_monthly: null,
    installs: 5671,
    rating: 4.7,
    rating_count: 267,
    tags: ['slack', 'notifications', 'alerts'],
    icon_color: 'yellow',
    featured: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mkt-009',
    name: 'PDF Reader Tool',
    description: 'Extracts text, tables, and metadata from PDFs for agent ingestion.',
    long_description: 'Advanced PDF processing tool that handles scanned documents via OCR, extracts structured tables, and chunks content for RAG pipelines.',
    category: 'tools',
    author: 'DocParse AI',
    author_verified: true,
    price_monthly: 500,
    installs: 3240,
    rating: 4.6,
    rating_count: 178,
    tags: ['pdf', 'ocr', 'documents', 'rag'],
    icon_color: 'red',
    featured: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mkt-010',
    name: 'Python Executor Skill',
    description: 'Runs Python code in a sandboxed environment and returns structured output.',
    long_description: 'Safe Python execution skill with access to NumPy, Pandas, Matplotlib, and SciPy. Returns stdout, stderr, figures, and variables as structured JSON.',
    category: 'skills',
    author: 'Space OS Team',
    author_verified: true,
    price_monthly: null,
    installs: 7430,
    rating: 4.9,
    rating_count: 502,
    tags: ['python', 'code-execution', 'data-science'],
    icon_color: 'blue',
    featured: true,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mkt-011',
    name: 'SQL Query Skill',
    description: 'Generates, validates, and executes SQL against connected databases.',
    long_description: 'End-to-end SQL skill. Translates natural language to SQL, validates against the schema, runs it safely, and formats results as markdown tables.',
    category: 'skills',
    author: 'Space OS Team',
    author_verified: true,
    price_monthly: null,
    installs: 4892,
    rating: 4.8,
    rating_count: 341,
    tags: ['sql', 'database', 'data'],
    icon_color: 'teal',
    featured: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mkt-012',
    name: 'Vision Analysis Skill',
    description: 'Describes, classifies, and extracts data from images using multimodal models.',
    long_description: 'Adds vision capabilities to any agent. Handles product photos, charts, UI screenshots, and documents. Returns structured JSON with labels, bounding boxes, and extracted text.',
    category: 'skills',
    author: 'VisionKit',
    author_verified: true,
    price_monthly: 700,
    installs: 2108,
    rating: 4.7,
    rating_count: 132,
    tags: ['vision', 'images', 'multimodal', 'ocr'],
    icon_color: 'pink',
    featured: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mkt-013',
    name: 'Sprint Planner Template',
    description: 'Pre-built sprint structure with backlog grooming, task breakdown, and review stages.',
    long_description: 'A complete sprint template with predefined agent roles, task templates, and review checkpoints. Import into any workspace and start your first sprint in minutes.',
    category: 'templates',
    author: 'Space OS Team',
    author_verified: true,
    price_monthly: null,
    installs: 3102,
    rating: 4.6,
    rating_count: 198,
    tags: ['sprint', 'planning', 'agile', 'template'],
    icon_color: 'indigo',
    featured: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mkt-014',
    name: 'Bug Fix Sprint',
    description: 'Structured sprint for triage, reproduction, fix, and regression testing of bugs.',
    long_description: 'A focused sprint template for bug-fixing cycles. Includes triage agent, reproduction task, patch task, QA agent, and regression test gate.',
    category: 'templates',
    author: 'Space OS Team',
    author_verified: true,
    price_monthly: null,
    installs: 1987,
    rating: 4.5,
    rating_count: 112,
    tags: ['bugs', 'sprint', 'qa', 'template'],
    icon_color: 'orange',
    featured: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: 'mkt-015',
    name: 'Zapier Bridge',
    description: 'Trigger 6,000+ Zapier automations from agent task completions.',
    long_description: 'Bidirectional Zapier integration. Trigger Zaps when tasks complete, and dispatch Space OS tasks from Zapier triggers. No code required.',
    category: 'integrations',
    author: 'Automate.io',
    author_verified: false,
    price_monthly: 1500,
    installs: 892,
    rating: 4.3,
    rating_count: 67,
    tags: ['zapier', 'automation', 'no-code', 'integrations'],
    icon_color: 'orange',
    featured: false,
    created_at: now,
    updated_at: now,
  },
]

export async function GET(req: NextRequest) {
  const category = req.nextUrl.searchParams.get('category')
  const search = req.nextUrl.searchParams.get('search')?.toLowerCase()

  let items = SEED_ITEMS

  if (category && category !== 'all') {
    items = items.filter((i) => i.category === category)
  }

  if (search) {
    items = items.filter(
      (i) =>
        i.name.toLowerCase().includes(search) ||
        i.description.toLowerCase().includes(search) ||
        i.tags.some((t) => t.includes(search))
    )
  }

  return NextResponse.json({ items, total: items.length })
}
